ServidorOptica/urls.py
from django.contrib import admin
from django.urls import path, include
from ServidorOptica import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('data/', include(('data.urls', 'data'), namespace='data')),
    path('', views.HomePageView.as_view(), name='home'),
    path('instrumentPrueba/', views.InstrumentPrueba,name='intrumentPrueba')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data/urls.py
from django.urls import path

from data import views

urlpatterns = [
    path(
        route='results',
        view=views.ResultsView.as_view(),
        name='results'
    ),
    path(
        route='user',
        view=views.UserHomeView.as_view(),
        name='user'
    ),
]

users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path(
        route='login',
        view=views.signin,
        name='login'
    ),
    path(
        route='requestAccess',
        view=views.requestAccess,
        name='requestAccess'
    ),
    path(
        route='logout',
        view=views.logoutUser,
        name='logout'
    )
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Optics ROJ</title>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <link
        href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
        rel="stylesheet">
</head>

<body id="body">
    <header class="header active-burguer" id="header">
        <div class="header-burguer-active">
            <figure class="logo">
                <img src="{% static 'images/IGP.png' %}" alt="igp">
            </figure>
            <figure class="close-logo logo">
                <a id="close-burguer" class="close-burguer" onclick="closeBurguer()">
                    <img class="close" src="{% static 'images/close.png' %}" alt="close">
                </a>
            </figure>
        </div>
        <nav class="menu">
            <ol>
                <li class="link">
                    <a href="/#home">Home</a>
                </li>
                <li class="link">
                    <a href="/#instruments">Instruments</a>
                </li>
                <li class="link">
                    <a href="/#database">Database</a>
                </li>
                <li class="link menu-contact">
                    <a href="/#contact">Contact Us</a>
                </li>
            </ol>
            <strong class="separation">
                |
            </strong>
                {%if request.user.is_authenticated %}
                    <a href="/users/logout" class="login-button">
                        Logout
                    </a>
                {% else%}
                    <a href="/users/login" class="login-button">
                        Login
                    </a>
                {%endif%}

        </nav>
    </header>
    <header class="header inactive-burguer" id="header">
        <div class="header-burguer-inactive">
            <figure class="burguer-figure logo">
                <a class="open-burguer" id="open-burguer" onclick="openBurguer()">
                    <img class="burguer" src="{% static 'images/menu.svg' %}" alt="burguer">    
                </a>
            </figure>
        </div>
    </header>
    {% block content%}
    {% endblock %}
    <footer class="footer" id="footer">
        <p class="quote">Instituto Geofísico del Perú, Ciencia para protegernos, ciencia para avanzar.</p>
        <p class="copyright">Copyright Jicamarca Radio Observatory</p>
    </footer>
    {% block script %}
    {% endblock%}
</body>

</html>

templates/home.html
{% extends "base.html"%}
{% load static %}
{% block content%}

<section class="hero" id="home">
                <img class="hero-image" src="{% static 'images/background.png' %}" alt="roj">
                <div class="hero-title">
                    <h1>OPTICS</h1>
                    <h2>Jicamarca Radio Observatory</h2>
                </div>
</section>
<section class="about-us">
            <div class="about-text">
                <h3>
                    About Us
                </h3>
                <p class="about-description">
                    The Optical Instrumentation Department of the Jicamarca Radio Observatory is part of CIELO or Cluster of Instruments for
                    Equatorial and Low-Latitude Observations.
                </p>
                <p class="about-description">
                    Under the watch of this team, there are Fabry Perot Interferometers and Allsky Imagers from different institutions such
                    us Clemson University, University of Illinois at Urbana Champaign, Boston University and the New Jersey Institute of
                    Technology.
                </p>
            </div>
            <div class="about-image">
                <img src="{% static 'images/red_fpi.png' %}" alt="map-fpi">
            </div>
</section>
<section class="instruments" id="instruments">
            <h3>Instruments</h3>
            <div class="intruments-container">
                <span><a class="changer" onclick="preView()"><</a></span>

            {% for instrument in instruments  %}
                    <a href="data/results" class="item" >
                        <figure>
                            <img src="{{instrument.instrumentImage.url}}" alt="instruments">
                            <span>{{instrument.instrumentName}}</span>
                        </figure>
                        <div class="instrument-footer">
                            <p> {{instrument.description}}</p>
                        </div>
                    </a>
            {% endfor %}
                <span><a class="changer" onclick="postView()">></a></span>
            </div>
</section>
<section class="database" id="database">
            <div></div>
            <h3>Database</h3>
            <div class="database-container">
                <div class="column-database column-type">
                    <h4>Instrument Type</h4>
                    {% for instrumentType in instrumentTypes %}
                        <a href="#database" class="button instrument-type">{{instrumentType}}</a>
                    {% endfor %}
                </div>
                <div class="column-database column-instrument">
                    <h4>Instrument</h4>
                    {% for instrumentASI in instrumentsASI %}
                        <a href="#database" class="button instrument-type">{{instrumentASI}}</a>
                    {% endfor %}
                </div>
                <div class="column-database column-date">
                    <h4>Date</h4>
                    <form action="#database" id="form-database" onsubmit="visibleShowResults(); return false;">
                        <div class="label">
                            <input type="date" name="from" id="from">
                        </div>
                        <input type="submit" value="Search Data" class="search-data" id="search-data">
                    </form>
                </div>
                <div class="show-results column-results">
                    <p id="data-available" class="data-available no-visible">Data available! <span class='show'> <a href='data/results'>Show Results</a> </span></p>
                </div>
            </div>
</section>
<section class="contact" id="contact">
            <h3>
                Contact Us
            </h3>
            <div class="contact-content">
                <div class="sitemap">
                    <h4>
                        Site Map
                    </h4>
                    <ol>
                        <li><a href="#">Home</a></li>
                        <li><a href="#instruments">Instrument</a></li>
                        <li><a href="#database">Database</a></li>
                        <li><a href="#">Sign in</a></li>
                        <li><a href="#">Sign up</a></li>
                    </ol>
                </div>
                <div class="socialmedia">
                    <h4>
                        Social Media
                    </h4>
                    <div class="socialsection">
                        <p><img class="img-fb" src="{% static 'images/fb.png' %}" alt="fb"><img src="{% static 'images/tt.png' %}"" alt="tt"><img src="{% static 'images/yt.png' %}" alt="yt"></p>
                        <p class="contact-adress">Calle Badajoz N° 169 Urb. Mayorazgo IV Etapa <br>
                        Ate, Lima 15012 - Perú. <br>
                        (51) 13172300</p>
                    </div>
                </div>
                <div class="mailing">
                    <form action="">
                        <input type="email" name="email" id="email" placeholder="E-mail">
                        <input type="text" name="message" id="message" placeholder="Message">
                        <input type="submit" value="Submit" id="contact-submit">
                    </form>
                </div>
            </div>
</section>

{% endblock%}

{%block script%}
    <script>
        window.onscroll = function () { myFunction() };
        
        function myFunction() {
            if (document.documentElement.scrollTop > 50) {
                document.getElementById("header").classList.add("header-activate");
            } else {
                document.getElementById("header").classList.remove("header-activate");
            }
        }

        var showResults = document.getElementById("data-available");
        function visibleShowResults() {
                visibleState(showResults, true);
        }

        function visibleState(object, state) {
                if (state) {
                    object.classList.remove("no-visible");
                }
                else {
                    object.classList.add("no-visible");
                }
        }

        // var n = 3   ;
        n = 0;
        actualPosition = 1;
        items = document.getElementsByClassName("item");
        nPositions = items.length - n + 1;
        
        function itemsDraw(n){
            nPositions = items.length - n + 1;
            for (i = 1; i <= items.length; i++) {
              //  console.log(i)
                if(actualPosition<=i && i<=actualPosition+n-1){
                    items[i-1].style.display = "block";
                }
                else{
                    items[i-1].style.display = "none";
                }
            }
        }

        function sizeWIndows23(x) {
                if (x.matches) { // If media query matches
                    console.log("MENOR A 980");
                    n = 2;
                    itemsDraw(2)
                } else {
                    console.log("mayor a 980");
                    n = 3;
                    itemsDraw(3)      
                }
            }
            function sizeWIndows12(y) {
                if (y.matches) { // If media query matches
                    console.log("mmenor a 630");
                    n = 1;
                    itemsDraw(1)
                }
            }

        var x = window.matchMedia("(max-width: 970px)")
        sizeWIndows23(x) 
        x.addListener(sizeWIndows23) 

        var y = window.matchMedia("(max-width: 630px)")
        sizeWIndows12(y) 
        y.addListener(sizeWIndows12) 
       

        function preView() {
            if (actualPosition != 1) {
                actualPosition = actualPosition - 1;
                itemsDraw(n)
            }
        }
        
        function postView() {
            if (actualPosition != nPositions) {
                actualPosition = actualPosition + 1;
                itemsDraw(n)
            }
        }

        inactiveBur = document.getElementsByClassName("inactive-burguer");
        activeBur = document.getElementsByClassName("active-burguer");

        function openBurguer(){
            inactiveBur[0].style.display = "none"
            activeBur[0].style.display = "inline"
        }
        function closeBurguer(){
            inactiveBur[0].style.display = "inline"
            activeBur[0].style.display = "none"
        }
    </script>

{% endblock %}

templates/instruments.html
{% extends "base.html"%}
{% load static%}
{% block content%}

<section class="results">
    <h2>
        FPI de Jicamarca
    </h2>
    <div class="container-results">
        <h3>
            Information
        </h3>
        <p>
            Name : Jicamarca FPI <br>
            Latitude : -11.95845 <br>
            Longitude : -76.8589 <br>
            Model : FPI <br>
        </p>
        <p>
            Located in Merihill, Lima. It is the nearest instrument to Jicamarca Radio Observatory.
        </p>
        <p>
            <img src="/media/data/instruments/instrumentNazca.jpg" alt="instruments">
        </p>
        <h3>
            Products
        </h3>
        <div class="product-list">
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
            <div class="product-container">
                <img src="{% static 'images/product.png'%}" alt="product">
                <p>Data_x_experiment.img</p>
            </div>
        </div>
    </div>
</section>

{%endblock%}

{%block script%}
<script>
    document.getElementById("header").classList.add("header-activate");
</script>
{%endblock%}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Optics ROJ</title>
    <link rel="stylesheet" href="styles/styles.css">
    <link
        href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
        rel="stylesheet">
</head>
<body>
    <header class="header">
        <figure class="logo">
            <img src="images/igp.png" alt="igp">
        </figure>
        <nav class="menu">
            <ol>
                <li class="link">
                    <a href="#home">Home</a>
                </li>
                <li class="link">
                    <a href="#instruments">Instruments</a>
                </li>
                <li class="link">
                    <a href="#database">Database</a>
                </li>
                <li class="link">
                    <a href="#contact">Contact Us</a>
                </li>
            </ol>
            <span class="link">
                <strong class="separation">
                    |
                </strong>
            </span>
            <span class="login link">
                Login
            </span>
        </nav>
    </header>
    <div class="content">
       <section class="login-content">
            <h2>Sign in</h2>
            <form action="#" method="POST">
                <input type="email" name="email" id="email-login" placeholder="E-mail">
                <input type="password" name="password" id="password-login" placeholder="********">
                <input type="button" value="Login">
            </form> 
       </section>
    </div>
    <section class="contact">
        <h3>
            Contact Us
        </h3>
        <div class="contact-content">
            <div class="sitemap">
                <h4>
                    Site Map
                </h4>
                <ol>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Instrument</a></li>
                    <li><a href="#">Database</a></li>
                    <li><a href="#">Sign in</a></li>
                    <li><a href="#">Sign up</a></li>
                </ol>
            </div>
            <div class="socialmedia">
                <h4>
                    Social Media
                </h4>
                <div class="socialsection">
                    <p><span>FB</span><span>Youtube</span><span>Twitter</span></p>
                    <p>Adress</p>
                </div>
            </div>
            <div class="mailing">
                <form action="#" method="POST">
                    <input type="email" name="email" id="email" placeholder="E-mail">
                    <input type="text" name="message" id="message" placeholder="Message">
                    <input type="button" value="Submit">
                </form>
            </div>
        </div>
    </section>
    <footer class="footer">
        <p class="quote">Instituto Geofísico del Perú, Ciencia para protegernos, ciencia para avanzar.</p>
        <p class="copyright">Copyright Jicamarca Radio Observatory</p>
    </footer>
</body>
</html>

templates/signin.html
{% extends "base.html"%}

{% load static%}

{%block content%}
<section class="login">
    <div class="container-log">
        <h2>
            Sign in
        </h2>
        <div class="information-log">
            <form method="POST" action="login">
                {% csrf_token %}
                <div class="info-item">
                    <label for="email">E-mail:</label>
                    <input type="email" name="email" id="email">
                </div>
                <div class="info-item">
                    <label for="pass">Password:</label>
                    <input type="password" name="pass" id="pass">
                </div>
                <input type="submit" value="Login" class="signin-button">
            </form>
            {% if error %}
                <p style="color: red";>{{error}}</p>
            {% endif %}
            <p>
                Do you need acces to database? <a href="{% url 'users:requestAccess' %}">Send a request here</a>
            </p>
        </div>
    </div>
</section>
{%endblock%}

{%block script%}
<script>

document.getElementById("header").classList.add("header-activate");
document.getElementById("footer").classList.add("footer-extra");

</script>
{% endblock %}



templates/signup.html

{% extends "base.html"%}

{% load static%}

{%block content%}
    <section class="login">
        <div class="container-log">
            <h2>
                Request for access to database
            </h2>
            <div class="information-log">
                <form action="{% url 'users:requestAccess'%}" method="POST">
                    {% csrf_token %}
                    <div class="info-item">
                        <label for="first">First Name:</label>
                        <input type="text" name="firstName" id="firstName" required="tue">
                    </div>
                    <div class="info-item">
                        <label for="last">Last Name:</label>
                        <input type="text" name="lastName" id="lastName" required="tue">
                    </div>
                    <div class="info-item">
                        <label for="institution">Institution:</label>
                        <input type="text" name="institution" id="institution" required="tue">
                    </div>
                    <div class="info-item">
                        <label for="institution">Why do you need acces to database?</label>
                        <input type="text" name="reasonToAccess" id="reasonToAccess" required="tue">
                    </div>
                    <div class="info-item">
                        <label for="email">E-mail:</label>
                        <input type="email" name="email" id="email" required="tue">
                    </div>
                    <input type="submit" value="Send Request" class="signin-button">
                </form>
                {% if error %}
                    <p style="color: red" ;>{{error}}</p>
                {% endif %}

                {% if form.errors %}
                    <p style="color: red" ;>{{form.errors}}</p>
                {% endif %}
                <p>
                    Do you have an account? <a href="{% url 'users:login'%}">Sign in here</a>
                </p>
            </div>
        </div>
    </section>
{%endblock%}

{%block script%}
<script>

    document.getElementById("header").classList.add("header-activate");
    document.getElementById("footer").classList.add("footer-extra");

</script>
{% endblock %}

